# SOCIETAL FACTORS (20 mins)
# Instructions / Notes: Read these carefully
This **Python Jupyter Notebook** notebook is split into the following sections:

1. **Initial section** with pre-filled cells, that you should run just to load some Python modules (packages), the dataset required for your task and its variables in memory.
2. **Middle section** with **description of a concrete task** associated with the dataset. 
3. **Final section (with one or more empty cells)** where you can perform analyses with the loaded dataset (e.g., write a few lines of code if needed), answer the question posed, and describe your reasoning in words.

**Read and execute each cell in order, without skipping forward**. To execute any cell, press **Shift+Enter** on your keyboard. It might take a couple of seconds to receive an output. 

Have fun!

In [1]:
# Run the following to import necessary packages and import dataset.
import pandas as pd
import numpy as np
import scipy as sp
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
matplotlib.style.use('ggplot')

d1 = "SC_dataset.csv"
df1 = pd.read_csv(d1)
#Print the dataset to see if is loaded properly.
df1

    Movie_theatres  Emigrants  Train_transport  Name_Peter
0              165      43980            90564         271
1              162      43481            86842         223
2              166      43466            88374         204
3              163      45017            89575         200
4              165      45869            90456         148
5              165      46786            90407         162
6              167      42708            88615         145
7              164      48171            91111         128
8              163      51988            92146         119
9              162      52097            92995         120
10             161      55782           103393          67
11             163      54907           106133          78
12             162      56416           109243          79
13             160      59226           111967          59
14             161      56340           114121          71

# DATASET DESCRIPTION
The dataset above contains various societal factors in **country 1** during a timespan of 2001 to 2015:
1. **Number of movie theaters**
2. **Number of emigrants (people leaving the country)** 
3. **Number of people transported by trains**
4. **Number of newborns given the name Peter** 

# TASK
Design **as many measures** to identify **strong AND meaningful** relationships among pairs of columns in this dataset. Your rationale should be based on consideration of every data point in the dataset. We expect you to **generate multiple measures**.

For **each measure that you design**: 

1. Please mark which relationships in the dataset are strong and meaningful (using yes/no)
2. Please provide a brief **reasoning** behind your answer (an explanation of **why** you took certain steps or performed certain calculations to get to the solution)
3. Please mark your **confidence** in the designed measure (on a scale of 1 to 5)

**MAKE SURE** to fill all three fields for each measure.

In [8]:
#Template for designing a measure. Make copies of this template cell to create as many measures as you are able to (within the allotted time).

#NOTE: Round all your statistics to 2 decimal places before reasoning with them!! 

for col1 in df1:
    for col2 in df1:
        if col1 == col2:
            continue

        print('corr between: {} and {} is {}'.format(col1, col2, df1[col1].corr(df1[col2])))

#REPORT YOUR ANSWER (e.g., yynnyy, yyynnn, ynynyy etc)
strong_and_meaningful_relationships = 'ynnyyy'
#Choose "y" for YES and "n" for NO for the 6 pairs of dataset relationships in the following sequence:
#MovieTheatres-Emigrants --> MovieTheatres-TrainTransport --> MovieTheatres-NamePeter --> Emigrants-TrainTransport --> Emigrants-NamePeter -->TrainTransport-NamePeter 
print(strong_and_meaningful_relationships)

#REPORT YOUR REASONING.
relationships_reasoning = 'Based on the correlation results'
print(relationships_reasoning)

#REPORT CONFIDENCE IN YOUR SOLUTION
confidence_measure = '324543' 
#Choose among: 1 (low confidence), 2, 3 (medium confidence), 4, 5 (high confidence)
print(confidence_measure)

corr between: Movie_theatres and Emigrants is -0.8034250982844886
corr between: Movie_theatres and Train_transport is -0.7084054458333855
corr between: Movie_theatres and Name_Peter is 0.5826269862226858
corr between: Emigrants and Movie_theatres is -0.8034250982844886
corr between: Emigrants and Train_transport is 0.913469786242309
corr between: Emigrants and Name_Peter is -0.8849072897539808
corr between: Train_transport and Movie_theatres is -0.7084054458333855
corr between: Train_transport and Emigrants is 0.9134697862423091
corr between: Train_transport and Name_Peter is -0.7963703520021375
corr between: Name_Peter and Movie_theatres is 0.5826269862226858
corr between: Name_Peter and Emigrants is -0.8849072897539807
corr between: Name_Peter and Train_transport is -0.7963703520021375
ynnyyy
Based on the correlation results
324543

In [9]:
#Template for designing a measure. Make copies of this template cell to create as many measures as you are able to (within the allotted time).

#NOTE: Round all your statistics to 2 decimal places before reasoning with them!! 

for col1 in df1:
    for col2 in df1:
        if col1 == col2:
            continue

        print('corr between: {} and {} is {}'.format(col1, col2, df1[col1].cov(df1[col2])))

#REPORT YOUR ANSWER (e.g., yynnyy, yyynnn, ynynyy etc)
strong_and_meaningful_relationships = 'None'
#Choose "y" for YES and "n" for NO for the 6 pairs of dataset relationships in the following sequence:
#MovieTheatres-Emigrants --> MovieTheatres-TrainTransport --> MovieTheatres-NamePeter --> Emigrants-TrainTransport --> Emigrants-NamePeter -->TrainTransport-NamePeter 
print(strong_and_meaningful_relationships)

#REPORT YOUR REASONING.
relationships_reasoning = 'None'
print(relationships_reasoning)

#REPORT CONFIDENCE IN YOUR SOLUTION
confidence_measure = 'None' 
#Choose among: 1 (low confidence), 2, 3 (medium confidence), 4, 5 (high confidence)
print(confidence_measure)

corr between: Movie_theatres and Emigrants is -9302.909523809523
corr between: Movie_theatres and Train_transport is -13717.609523809522
corr between: Movie_theatres and Name_Peter is 75.28095238095237
corr between: Emigrants and Movie_theatres is -9302.909523809523
corr between: Emigrants and Train_transport is 50364619.72380952
corr between: Emigrants and Name_Peter is -325557.05238095234
corr between: Train_transport and Movie_theatres is -13717.609523809522
corr between: Train_transport and Emigrants is 50364619.72380952
corr between: Train_transport and Name_Peter is -489967.8238095238
corr between: Name_Peter and Movie_theatres is 75.28095238095237
corr between: Name_Peter and Emigrants is -325557.05238095234
corr between: Name_Peter and Train_transport is -489967.8238095238
ynnyyy
Based on the correlation results
324543

In [ ]:
#ONLY use this space below to write your code (if needed) for any measure you generate. DO NOT ERASE this code segment from the workbook.












#Your intuitive ideas are valuable!!If you need syntax-related help in implementing your ideas, you can access the following documentation files (use the "Search" tab for queries) and/or summarized syntax sheets.

#a) Pandas library
#Documentation file: https://pandas.pydata.org/pandas-docs/stable/
#Syntax sheet: https://datacamp-community-prod.s3.amazonaws.com/fbc502d0-46b2-4e1b-b6b0-5402ff273251

#b) Numpy library
#Documentation file: https://docs.scipy.org/doc/numpy/user/index.html
#Syntax sheet: https://datacamp-community-prod.s3.amazonaws.com/e9f83f72-a81b-42c7-af44-4e35b48b20b7

#c) Matplotlib library
#Documentation file: https://matplotlib.org/contents.html
#Syntax sheet: https://datacamp-community-prod.s3.amazonaws.com/28b8210c-60cc-4f13-b0b4-5b4f2ad4790b

#d) Scipy library
#Documentation file: https://docs.scipy.org/doc/scipy/reference/
#Syntax sheet: https://datacamp-community-prod.s3.amazonaws.com/5710caa7-94d4-4248-be94-d23dea9e668f